### register

POST http://localhost/api/auth/register
Content-Type: application/json

{
    "email": "scott@gmail.com",
    "password": "tiger",
    "confirm_password": "tiger"
}

### login

POST http://localhost/api/auth/login
Content-Type: application/json

{
    "email": "scott@gmail.com",
    "password": "tiger"
}